{
  "formatVersion": "1.1",
  "component": {
    "group": "powerdancer.serializable",
    "module": "serializable",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "uandgwy6svfdja5sp6oojjv2na"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "serializable-1.0.jar",
          "url": "serializable-1.0.jar",
          "size": 9813,
          "sha512": "f64906ed994948237067289ca5b6a7595aa6e3f977a5943322705331ecfb15931915b8ace284178096fa62c327fa718ecf40f4c08341630b545189e1ab5220c7",
          "sha256": "77da13c1b5064da68c8f3224fbb48d6071d5c80d9a6b19063433aba2d86c8106",
          "sha1": "ec2a319034d011d1e2bff35095bee0010ba82182",
          "md5": "236cd65882f24cde484657f4b165b347"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "serializable-1.0.jar",
          "url": "serializable-1.0.jar",
          "size": 9813,
          "sha512": "f64906ed994948237067289ca5b6a7595aa6e3f977a5943322705331ecfb15931915b8ace284178096fa62c327fa718ecf40f4c08341630b545189e1ab5220c7",
          "sha256": "77da13c1b5064da68c8f3224fbb48d6071d5c80d9a6b19063433aba2d86c8106",
          "sha1": "ec2a319034d011d1e2bff35095bee0010ba82182",
          "md5": "236cd65882f24cde484657f4b165b347"
        }
      ]
    }
  ]
}
